### ISSUE TITLE
minify files from exporting folder

### ISSUE THREAD

**Issue by piernik** [arturgspb/bower-amcharts#16]
As in topic. In `exporting` folder there are not minified versions.
Can You add minified ones?

**Comment by arturgspb** [comment]
Hi! Unfortunately, in the next couple of months I will not be able to add js minifier for builds.
Can you help me with this?

**Comment by olakara** [comment]
@piernik , recent release of amCharts have minified js with them.. update the library and you should find all the necessary files under 'plugins/export' folder.
