### ISSUE TITLE
No tag available for latest updates..

### ISSUE THREAD

**Issue by olakara** [arturgspb/bower-amcharts#19]
Hi, There is no tag available for the latest version 3.14.5.. Here is the error you get when you try to get latest.. 

$ bower install amcharts#3.14.5 --save
bower amcharts#3.14.5       not-cached git://github.com/arturgspb/bower-amcharts.git#3.14.5
bower amcharts#3.14.5          resolve git://github.com/arturgspb/bower-amcharts.git#3.14.5
bower amcharts#3.14.5     ENORESTARGET No tag found that was able to satisfy 3.14.5

Additional error details:
Available versions: 3.14.3, 3.14.2, 3.14.1, 3.13.3, 3.13.2, 3.13.0, 3.11.3, 3.11.2, 3.10.3, 3.10.0, 3.4.6

Can you please create a tag for the latest version?

**Comment by arturgspb** [comment]
I'm sorry! Apparently, I accepted your request (https://github.com/arturgspb/bower-amcharts/pull/17) not to create a tag.

fix
https://github.com/arturgspb/bower-amcharts/tree/3.14.5
